### ISSUE TITLE
Should we use the input with type="url" for the main input?

### ISSUE THREAD

**Issue by Valve** [gradejs/gradejs#29]
By using the `url` type we'll make the keyboard on mobile devices different and not auto-capitalize etc.
We can disable the html form validation with `novalidate` attribute on the input too so that it doesn't complain when no scheme is provided.
What do you think?

**Comment by spalt08** [comment]
Sounds reasonable, thanks. 

@ctizen can you please add this feature for the pending UI changes you are currently working on?
